### ISSUE TITLE
Error on Payment Option "None"

### ISSUE THREAD

**Issue by Artemis001** [garrya100/Apple-ID-Creator-Universal#3]
Hi there,

Got a few IDs made and then started getting an error on the None payment option that is stopping the ID from creating, not sure if this is an error on my side or something to do with iTunes.

**Comment by ChickenBeard** [comment]
Is this in the US Apple Store?    What version of iTunes?  I've used it successfully up to 12.1.2 but I haven't tried with yesterday's 12.2 update yet.  
Also, it happened in the middle of processing the list of Apple IDs?  (i.e. it cranked along file for  a few then suddenly broke?).

**Comment by Artemis001** [comment]
Hi ChickenBeard,

This is all with the Australian iTunes Store. 

When I posted this I was on 12.1.2 and yes it happened after 5 IDs were successfully created. The script ran until all the IDs in my CSV had been processed and threw no errors when the payment option didn't work. 

After the update to OSX 10.10.4 and iTune 12.2 I know get the script error - "can't get menu bar item "Store" of menu bar 1 of application process "ITunes".

**Comment by garrya100** [comment]
Hi Artemis

Have you had you IP whitelisted by Apple? If not you can only generate 5 ID's before your IP is blocked from generating more.
