### ISSUE TITLE
change store to accounts for 12.2

### ISSUE THREAD

**Issue by lukeneff** [garrya100/Apple-ID-Creator-Universal#4]
New to the GitHub game, so apologies if doing it wrong. Works great except for set storeMenu should now go to "Account" instead of "Store".

Thanks for sharing this.

**Comment by garrya100** [comment]
Thanks lukeneff, I'm away from my development machines this week, I'll fix that up and release a new version next week

**Comment by lukeneff** [comment]
Sounds great. Thank you. I also ran into an issue where it wasn't enough to be whitelisted... instead I also had to send them the complete list of emails I was going to use through the script. The guy I spoke with on the phone mumbled something about changed security / spamming filters.

**Comment by JohnnyAction** [comment]
Love this script - it's been working great for months.  Thank you!
Any ETA when you'll have one ready for 12.2?

**Comment by lukeneff** [comment]
@JohnnyAction I got this one working with 12.2 with one small change: set storeMenu should now go to "Account" instead of "Store." I also found out that I had to whitelist all the email addresses ahead of time — not just the domain whitelisting. Other than that, it worked beautifully.

**Comment by JohnnyAction** [comment]
Perfect.  That worked.  Thank you very much :)

**Comment by garrya100** [comment]
Updated script to enable it to work with iTunes 12.1 and 12.2 families. Will Apple change it again with the next version?
